cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:celestial_obj_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:celestial_obj_id>/', views.cart_remove, name='cart_remove'),
]

celestial_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

CELESTIAL_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]

class CartAddCelestialForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=CELESTIAL_QUANTITY_CHOICES,
                                      coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from main.models import Celestial
from .forms import CartAddCelestialForm


@require_POST
def cart_add(request, celestial_obj_id):
    cart = Cart(request)
    celestial_obj = get_object_or_404(Celestial, id=celestial_obj_id)
    form = CartAddCelestialForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(celestial_obj=celestial_obj,
                 quantity=cd['quantity'],
                 override=cd['override'])
    return redirect('cart:cart_detail')
    

@require_POST
def cart_remove(request, celestial_obj_id):
    cart = Cart(request)
    celestial_obj = get_object_or_404(Celestial, id=celestial_obj_id)
    cart.remove(celestial_obj)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', context={'cart': cart})

cart/templates/cart/cart_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block content %}
    <section class="cart d-flex">
        <div class="cart-title">
            <h2>Shopping Cart</h2>
        </div>
        <div class="cart-cards">
            {% for item in cart %}
                {% with celestial_obj=item.celestial_obj %}
                    <div class="cart-card d-flex">
                        <div class="cart-card-img">
                            <img src="{{ celestial_obj.image.url }}" alt="">
                        </div>
                        <div style="width: 490px; height: 125px; display: flex; justify-content: space-between;">
                            <div class="cat-view">
                                <div class="cart-card-info">
                                    <div class="cart-card-name ">
                                        <p>{{ celestial_obj.name }}</p>
                                    </div>
                                    <div class="cart-card-q">
                                        <p style="font-size:18px; padding-left: 20px; margin-top: 5px;">Quantity: {{ item.quantity }}</p>
                                    </div>
                                </div>
                                
                                <div class="cart-card-price">
                                    {% if celestial_obj.discount %}
                                        
                                        <div class="cart-discount d-flex gap-2">
                                            <p style="font-size:20px;">Price: </p>
                                            <p class="line">&#8383; {{ celestial_obj.price }}</p>
                                            <p class="price pt-2">&#8383; {{ celestial_obj.cell_price }}</p>
                                        </div>
                                    {% else %}
                                        <p>Price: </p>
                                        <p class="price mt-2">$ {{ celestial_obj.price }}</p>
                                    {% endif %}
                                </div>
    
    
                            </div>

                            <div style="align-self : flex-end;">
                                <form action="{% url "cart:cart_remove" celestial_obj.id %}" method="post">
                                    <input type="submit" value="Remove" class="remove-btn">
                                    {% csrf_token %}
                                </form>

                            </div>

                            

                        </div>
                        
                        
                        
                    </div>
                {% endwith %}
            {% endfor %}
        </div>
        <div class="total">
            <h5>Total sum: $ {{ cart.get_total_price }}</h5>
        </div>
        <div class="cart-buttons d-flex gap-3">
            <a href="#" class="cart-btn">Continue Shopping</a>
            
        </div>
    </section>
{% endblock content %}