cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:celestial_obj_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:celestial_obj_id>/', views.cart_remove, name='cart_remove'),
]

celestial_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images/%Y%m%d', blank=True, null=True)

    class Meta:
        db_table = 'user'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    class Meta:
        model = User 
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )

class UserProfileForm(UserChangeForm):
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()    
    
    class Meta:
        model = User 
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'image',
        )
    
    

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_POST
from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.contrib.auth import authenticate
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required



def login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
            return HttpResponseRedirect(reverse('main:category_list'))  
    else:
        form = UserLoginForm()
        return render(request, 'users/login.html', context={'form': form})


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login')) 


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user = form.instance
            login(request, user)
            messages.success(request, f'{user.username}, Successful Registration')
            return HttpResponseRedirect(reverse('user:login'))
    else:
        form = UserRegistrationForm()
    return render(request, 'users/registration.html')


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, isinstance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile was changed')
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    return render(request, 'users/profile.html', {'form': form})

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
    <div class="container-login">
        <section class="login d-flex">
            <div class="login-title">
                <h2>Login</h2>
                <form action="{% url "user:login" %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label form-style">Username</label>
                        <input type="text" class="form-control form-style"
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        name="username" id="id_username" placeholder="Input username" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label form-style">Password</label>
                        <input type="password" class="form-control form-style"
                        name="password" id="id_password" placeholder="Your password" required>
                    </div>
                    <button type="submit" class="login-btn form-style">Login</button>
                </form>
                <div class="reset-pass">
                    <hr>
                    <div class="mt-3">
                        <a href="#">Reset Password</a> | <a href="{% url "user:registration" %}">Create Account</a>
                    </div>
                </div>
            </div>
        </section>
    </div>
    
{% endblock content %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block content %}
    <div class="container-profile">
        <div class="windowp d-flex p-4 mb-4 mx-2 rounded">
            <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                <h2 class="mb-2">Profile</h2>
                {% csrf_token %}
                <div class="d-flex">
                    <div class="1box">
                        <div class="col-md-12 mb-3">
                            {% if user.image %}
                                <img src="{{ user.image.url }}" alt="Avatar" class="img-fluid"
                                style="max-width: 150px; max-height: 150px;">
                            {% else %}
                                <img src="{% static 'img/user.jpg' %}" alt="Avatar" class="img-fluid"
                                style="max-width: 150px; max-height: 150px;">
                            {% endif %}
                            <input type="file" class="form-control form-styleprofile mt-2" id="id_image"
                            name="image" accept="image/*">
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_first_name" class="form-label">First Name</label>
                            <input type="text" class="form-control form-styleprofile" id="id_first_name"
                            name="first_name" placeholder="Your First Name" value="{{ form.first_name.value }}"
                            required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_last_name" class="form-label">Last Name</label>
                            <input type="text" class="form-control form-styleprofile" id="id_last_name"
                            name="last_name" placeholder="Your Last Name" value="{{ form.last_name.value }}"
                            required>
                        </div>
                    </div>
                    <div class="box2">
                        <div class="col-md-12 mb-3">
                            <label for="id_username" class="form-label">Username</label>
                            <input type="text" class="form-control form-styleprofile" id="id_username"
                            name="username" placeholder="Your Username" value="{{ form.username.value }}"
                            required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" class="form-control form-styleprofile" id="id_email"
                            name="email" placeholder="Your Email" value="{{ form.email.value }}"
                            required>
                        </div>
                    </div>
                </div>
                <div class="btns d-flex gap-4 mt-4">
                    <button type="submit" class="profile-btn">Save</button>
                    <a class="profile-btn" href="{% url "user:logout" %}">Logout</a>
                </div>
                
            </form>
            
        </div>
    </div>
{% endblock content %}

users/templates/users/registration.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Registration{% endblock title %}

{% block content %}
    <div class="container-registration">
        <section class="login-reg d-flex">
            <div class="login-title">
                <h2>Registration</h2>
                <form action="{% url "user:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label form-stylereg">First Name</label>
                            <input type="text" class="form-control form-stylereg" id="id_first_name"
                            value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                            name="first_name" placeholder="Your First Name" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label form-stylereg">Last Name</label>
                            <input type="text" class="form-control form-stylereg" id="id_last_name"
                            value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                            name="last_name" placeholder="Your Last Name" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label form-stylereg">Username</label>
                            <input type="text" class="form-control form-stylereg" id="id_username"
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                            name="username" placeholder="Your Username" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label form-stylereg">Email</label>
                            <input type="email" class="form-control form-stylereg" id="id_email"
                            value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                            name="email" placeholder="Your Email" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label form-stylereg">Password</label>
                            <input type="password" class="form-control form-stylereg" id="id_password1"
                            value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                            name="password1" placeholder="Your Password" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label form-stylereg">Confirm Password</label>
                            <input type="password" class="form-control form-stylereg" id="id_password2"
                            value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                            name="password2" placeholder="Your Password" required>
                        </div>
                    </div>
                    <button type="submit" class="login-btn form-style">Register</button>
                </form>
            </div>
        </section>


    </div>
    
{% endblock content %}