cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:celestial_obj_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:celestial_obj_id>/', views.cart_remove, name='cart_remove'),
]

celestial_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop', views.category_list, name='category_list'),
    path('shop/category/<slug:category_slug>/', views.category_list, name='category_list'),
    path('shop/<slug:detail_slug>/', views.detail, name='detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
]

main/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=25, unique=True)
    slug = models.SlugField(max_length=25, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['slug'])]
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:category_list", kwargs={"category_slug": self.slug})
    
    

class Celestial(models.Model):
    category = models.ForeignKey(Category, verbose_name='celestial', on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    discount = models.DecimalField(max_digits=4, default=0.00, decimal_places=2)
    created =  models.TimeField(auto_now_add=True)
    updated = models.TimeField(auto_now=False)
    image = models.ImageField(upload_to='celestial/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['id', 'slug']), 
                   models.Index(fields=['name'])]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("main:detail", kwargs={"detail_slug": self.slug})
    
    def cell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        return self.price


class ImageCelestial(models.Model):
    celestial_obj = models.ForeignKey(Celestial, related_name='images', on_delete=models.PROTECT, null=True)
    image = models.ImageField(upload_to='celestial/%Y/%m/%d', blank=True)
    
    def __str__(self):
        return f'{self.celestial_obj.name} - {self.image.name}'
    

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Celestial
from django.core.paginator import Paginator
from cart.forms import CartAddCelestialForm

# Create your views here.

def index(request):
    celestial_objs = Celestial.objects.filter(available=True)
    return render(request, 'main/index.html', context={'celestial_objs': celestial_objs})

def category_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    celestial_objs = Celestial.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        celestial_objs = Celestial.objects.filter(category=category)
    paginator = Paginator(celestial_objs, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'main/category_list.html', context={'category': category,
                                                               'celestial_objs': celestial_objs,
                                                               'categories': categories,
                                                               'page_obj': page_obj})

def detail(request, detail_slug):
    celestial_obj = get_object_or_404(Celestial, slug=detail_slug)
    cart_celestial_form = CartAddCelestialForm
    return render(request, 'main/detail.html', context={'celestial_obj': celestial_obj,
                                                        'cart_celestial_form': cart_celestial_form})

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap\css\bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'img/ico2.ico' %}" type="image/x-icon">
</head>
<body>
    <header class="header sticky-top">
        <div class="header-container d-flex">
            <nav class='header-nav pt-3'>
                <ul class="header-list d-flex">
                    <li><a href="{% url 'main:index' %}"><img src="{% static 'img/logo.png' %}" class="header-logo-img" alt="logo"></a></li>
                    <li>
                        <a href="{% url 'main:index' %}" class="nav-a m-3">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'main:category_list' %}"  class="nav-a m-3">Shop</a>
                    </li>
                </ul>
            </nav>
            <div class="header-logo">
                <a href="#"><img src="#" class="bottom-img" alt="--"></a>
            </div>
            <div class="header-profile d-flex pt-3">
                <div class="staff d-flex">
                    <div class="header-top-phone d-flex">
                        <i class="fa-solid fa-mobile-screen-button m-1"></i>
                        <a href="tel:+1234567890" class="tel"><p>+123-456-78-90</p></a>
                    </div>
                    <div class="header-top-icons">
                        <ul class="social-icons d-flex">
                            <li><a href="#"><i class="fa-brands m-1 fa-youtube"></i></a></li>
                            <li><a href="#"><i class="fa-brands m-1 fa-x-twitter"></i></a></li>
                            <li><a href="#"><i class="fa-brands m-1 fa-instagram"></i></a></li>
                        </ul>
                    </div>
                    <div class="btn-group">
                        <div class="dropdown d-flex">
                            <button class="btn btn-group-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                en
                            </button>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="#">ru</a></li>
                            </ul>
                          </div>
                    </div>
                </div>               
                <div class="header-user d-flex">
                    <a href="{% url "cart:cart_detail" %}"><img src="{% static 'img/cart_v2.png' %}" class="cart-img" alt="cart"></a>
                    {% if user.is_authenticated %}
                        <a href="{% url "users:profile" %}">Profile</a>
                        <p> | </p>
                        <a href="{% url "users:logout" %}">Logout</a>
                    {% else %}
                        <a href="{% url "users:login" %}" class="m-2">Login</a>
                    {% endif %}
                    <p class="cart-quantity">
                        {% with cart_quantity=cart|length %}
                            {% if cart_quantity > 0 %}
                                {{cart_quantity}}
                            {% else %}
                            0
                            {% endif %}
                        {% endwith %}
                    </p>
                </div>     
            </div>
        </div>
    </header>
  
    <section class='space'>
        
        
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </section>
    
    <div class="content" style="position: fixed; top: 90px; width: 100%; align-items: center;">
        {% block content %}
        {% endblock content %}
    </div>
    
    <script src="{% static 'bootstrap\js\bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/category_list.html
{% extends "main/base.html" %}
{% load static %}


{% block title %}
Celestial shop
{% endblock title %}

{% block content %}
    <div class="list d-flex">
        <div class="sidebar">
            <h3>Categories</h3>
            <nav class="category_list">
                <ul class="cats">
                    <li {% if not category %} class="selected"{% endif %}>
                        <a href="{% url 'main:category_list' %}" class="all_cat_list">All category</a>
                    </li>
                    {% for category in categories %}
                        
                            <li {% if category == category_slug %}class="selected"{% endif %}>
                                <a href="{{ category.get_absolute_url}}">{{ category.name }}</a>
                            </li>
                        
                    {% endfor %}
                </ul>
            </nav>
        </div>
        <div class="main">
            <div class="main-title">
                {% if category %}{{ category.name }}{% else %}Celestial objects{% endif %}
            </div>
            <div class="celestial-list">
                <div class="items">
                    {% for celestial_obj in celestial_objs %}
                        <div class="item">
                            <a href="{{ celestial_obj.get_absolute_url}}" class="index-card d-flex flex-column align-items-center text-center">
                                <img src="{{ celestial_obj.image.url }}" class="card-img" alt="">
                                <h5 class="title-card">{{ celestial_obj.name }}</h5>
                                {% if celestial_obj.discount %}
                                    <div class="cart-discount d-flex gap-2">
                                        <p class="line">&#8383; {{ celestial_obj.price }}</p>
                                        <p class="price pt-2">&#8383; {{ celestial_obj.cell_price }}</p>
                                    </div>
                                {% else %}
                                    <p class="price">$ {{ celestial_obj.price }}</p>
                                {% endif %}
                            </a>   
                        </div>
                    {% endfor %}         
                </div>
            </div>
            
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="">
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                </li>
                {% endif %}
                {% for page in page_obj.paginator.page_range %}
                    {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                    <li>
                        <a href="?page={{ page }}" class="{% if page_obj.number == page %}disabled{% endif %}">{{ page }}</a>
                    </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="">              
                    <a href="?page=1">&laquo; last</a>
                    <a href="?page={{ page_obj.next_page_number }}">next</a>                
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock content %}

main/templates/main/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}{{ celestial_obj.name }}{% endblock title %}


{% block content %}
    <div class="detail d-flex">
        <div class="detail-img">
            
            {% for image in celestial_obj.images.all %}
                <img src="{{ image.image.url }}" class="detail-image" alt="" style="display: none;" data-index="{{ forloop.counter0 }}">
            {% endfor %}
            <div class="image-nav">
                <button class="prev-btn">&lsaquo;</button>
                <button class="next-btn">&rsaquo;</button>
            </div>
        </div>
        <script>
            const images = document.querySelectorAll('.detail-image');
            const prevBtn = document.querySelector('.prev-btn');
            const nextBtn = document.querySelector('.next-btn');
            let currentIndex = 0;

            images[currentIndex].style.display = 'block';

            if (images.length === 1) {
                prevBtn.style.display = 'none';
                nextBtn.style.display = 'none';
            } else {
                prevBtn.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex - 1 + images.length) % images.length;
                    images[currentIndex].style.display = 'block';
                });

                nextBtn.addEventListener('click', () => {
                    images[currentIndex].style.display = 'none';
                    currentIndex = (currentIndex + 1) % images.length;
                    images[currentIndex].style.display = 'block';
                });
            }
        </script>
        <div class="detail-card">
            <h2>{{ celestial_obj.name }}</h2>
            <h3>Category: {{ celestial_obj.category }}</h3>
            <div class='detail-p'><p>{{ celestial_obj.description|linebreaks }}</p></div>
            {% if celestial_obj.discount %}
                <div class="card-discount d-flex gap-2">
                    <p class="line">&#8383; {{ celestial_obj.price }}</p>
                    <p class="price">&#8383; {{ celestial_obj.cell_price }}</p>
                </div>
            {% else %}
                <p class="price">&#8383; {{ celestial_obj.price }}</p>
            {% endif %}
            <form action="{% url "cart:cart_add" celestial_obj.id %}" class="qform" method="post">
                <div class="cart-form">
                    {{ cart_celestial_form }}
                    {% csrf_token %}
                </div>
                <input type="submit" class="add-to-cart-btn" value="Add to cart">
            </form>
        </div>
    </div>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Celestial shop{% endblock title %}


{% block content %}
    <div class="index d-flex flex-column">
        <div class="index-title flex-column align-items-center">
            <p>Today it’s worth thinking about the global, think well and choose your place in this galaxy!</p>
            <p>don't forget to look at the price! gl...</p>
        </div>
        <div class="index-recommendations pb-4">
            <div class="rec-title mb-4">
                <h3 class="most-pop">Popular Celestial objects</h3>
            </div>
        </div>
        <div class="index-cards d-flex gap-4">
            {% for celestial_obj in celestial_objs %}
                {% if celestial_obj.discount %}
                    <a href="{{ celestial_obj.get_absolute_url}}" class="index-card d-flex flex-column align-items-center text-center">
                        <img src="{{ celestial_obj.image.url }}" class="card-img" alt="">
                        <h5 class="title-card">{{ celestial_obj.name }}</h5>
                        <div class="cart-discount d-flex gap-2">
                            <p class="line">&#8383; {{ celestial_obj.price }}</p>
                            <p class="price pt-2">&#8383; {{ celestial_obj.cell_price }}</p>
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}